In [5]:
install.packages("readr")

Installing package into 'C:/Users/miche/AppData/Local/R/win-library/4.6'
(as 'lib' is unspecified)

also installing the dependencies 'bit', 'prettyunits', 'pkgconfig', 'magrittr', 'bit64', 'tidyselect', 'progress', 'clipr', 'hms', 'R6', 'tibble', 'vroom', 'withr', 'cpp11', 'tzdb'

package 'bit' successfully unpacked and MD5 sums checked
package 'prettyunits' successfully unpacked and MD5 sums checked
package 'pkgconfig' successfully unpacked and MD5 sums checked
package 'magrittr' successfully unpacked and MD5 sums checked
package 'bit64' successfully unpacked and MD5 sums checked
package 'tidyselect' successfully unpacked and MD5 sums checked
package 'progress' successfully unpacked and MD5 sums checked
package 'clipr' successfully unpacked and MD5 sums checked
package 'hms' successfully unpacked and MD5 sums checked
package 'R6' successfully unpacked and MD5 sums checked
package 'tibble' successfully unpacked and MD5 sums checked
package 'vroom' successfully unpacked and MD5 sums checked
package 'withr' successfully unpacked and MD5 sums checked
package 'cpp11' successfully unpacked and MD5 sums checked
package 'tzdb' successfully unpacked and MD5 sums checked
package 'readr' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\miche\AppData\Local\Temp\RtmpWWlLh5\downloaded_packages

In [6]:
library(readr)

In [11]:
readLines("../data/ABM_Unit4_model7 social-influence-experiment-table.csv", n = 10)

 [1] "\"BehaviorSpace results (NetLogo 7.0.4)\",\"Table version 2.0\""
 [2] "\"ABM_Unit4_model7.nlogox\""
 [3] "\"social-influence-experiment\""
 [4] "\"07/08/2026 16:45:24:111 +0200\""
 [5] "\"min-pxcor\",\"max-pxcor\",\"min-pycor\",\"max-pycor\""
 [6] "\"-16\",\"16\",\"-16\",\"16\""
 [7] "\"[run number]\",\"broadcast\",\"density\",\"social\",\"frac-influential\",\"m\",\"network\",\"influential-weight\",\"[step]\",\"count turtles with [adopted?]\",\"count regulars with [adopted?]\",\"count influentials with  [adopted?]\""
 [8] "\"2\",\"0.01\",\"0.3\",\"0.1\",\"0.25\",\"100\",\"random\",\"0.7\",\"0\",\"0\",\"0\",\"0\""
 [9] "\"6\",\"0.01\",\"0.3\",\"0.1\",\"0.25\",\"100\",\"random\",\"0.7\",\"0\",\"0\",\"0\",\"0\""
[10] "\"1\",\"0.01\",\"0.3\",\"0.1\",\"0.25\",\"100\",\"random\",\"0.7\",\"0\",\"0\",\"0\",\"0\""

In [21]:
data = read_csv("../data/ABM_Unit4_model7 social-influence-experiment-table.csv", skip=6)

Rows: 2521 Columns: 12
── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr  (1): network
dbl (11): [run number], broadcast, density, social, frac-influential, m, inf...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [22]:
head(data)

  [run number] broadcast density social frac-influential m   network
1 2            0.01      0.3     0.1    0.25             100 random
2 6            0.01      0.3     0.1    0.25             100 random
3 1            0.01      0.3     0.1    0.25             100 random
4 4            0.01      0.3     0.1    0.25             100 random
5 3            0.01      0.3     0.1    0.25             100 random
6 2            0.01      0.3     0.1    0.25             100 random
  influential-weight [step] count turtles with [adopted?]
1 0.7                0      0
2 0.7                0      0
3 0.7                0      0
4 0.7                0      0
5 0.7                0      0
6 0.7                1      0
  count regulars with [adopted?] count influentials with  [adopted?]
1 0                              0
2 0                              0
3 0                              0
4 0                              0
5 0                              0
6 0                              0

In [23]:
colnames(data) <- c("run","social","weight","m","network","frac.inf","broadcast", "density","step","adoptions","reg.adoptions","inf.adoptions")

In [24]:
head(data)

  run social weight m   network frac.inf broadcast density step adoptions
1 2   0.01   0.3    0.1 0.25    100      random    0.7     0    0
2 6   0.01   0.3    0.1 0.25    100      random    0.7     0    0
3 1   0.01   0.3    0.1 0.25    100      random    0.7     0    0
4 4   0.01   0.3    0.1 0.25    100      random    0.7     0    0
5 3   0.01   0.3    0.1 0.25    100      random    0.7     0    0
6 2   0.01   0.3    0.1 0.25    100      random    0.7     1    0
  reg.adoptions inf.adoptions
1 0             0
2 0             0
3 0             0
4 0             0
5 0             0
6 0             0

In [33]:
agg.data <- aggregate(data, by = list(data$step,data$social),FUN=mean)

Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"

In [28]:
head(agg.data)

  Group.1 Group.2 run  social weight m    network frac.inf broadcast density
1 0       0.01    50.5 0.01   0.3    0.55 0.25    100      NA        0.7
2 1       0.01    50.5 0.01   0.3    0.55 0.25    100      NA        0.7
3 2       0.01    50.5 0.01   0.3    0.55 0.25    100      NA        0.7
4 3       0.01    50.5 0.01   0.3    0.55 0.25    100      NA        0.7
5 4       0.01    50.5 0.01   0.3    0.55 0.25    100      NA        0.7
6 5       0.01    50.5 0.01   0.3    0.55 0.25    100      NA        0.7
  step adoptions reg.adoptions inf.adoptions
1 0     0.00      0.00         0.00
2 1     1.44      1.08         0.36
3 2     3.56      2.69         0.87
4 3     6.95      5.14         1.81
5 4    11.61      8.80         2.81
6 5    18.95     14.54         4.41

In [36]:
with(agg.data([agg.data$social == 0.1,]), plot(step,adoptions,type="l"))

ERROR: Error in parse(text = input): <text>:1:15: unexpected '['
1: with(agg.data([
                  ^

In [ ]:
# this last part is different from the video (check 1. simulation params, 2. names columns and 3. aggregate function)